// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4K7rNkB5OPt9vT50jksYtHGJT4HBwsjM',
    appId: '1:317997860745:web:2208eac2e7f63d5f934358',
    messagingSenderId: '317997860745',
    projectId: 'food-delivery-app-31c7f',
    authDomain: 'food-delivery-app-31c7f.firebaseapp.com',
    storageBucket: 'food-delivery-app-31c7f.appspot.com',
    measurementId: 'G-LEDBCH1DLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbK9XqSackE58H82Rs4mFtw7xcUIJT88Q',
    appId: '1:317997860745:android:31f8ff91da176260934358',
    messagingSenderId: '317997860745',
    projectId: 'food-delivery-app-31c7f',
    storageBucket: 'food-delivery-app-31c7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Y6GGApqnS_NbH2tM4UttVSCOWgdWhpw',
    appId: '1:317997860745:ios:b725002ce880364a934358',
    messagingSenderId: '317997860745',
    projectId: 'food-delivery-app-31c7f',
    storageBucket: 'food-delivery-app-31c7f.appspot.com',
    iosBundleId: 'com.codeforany.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7Y6GGApqnS_NbH2tM4UttVSCOWgdWhpw',
    appId: '1:317997860745:ios:6b990983fd044040934358',
    messagingSenderId: '317997860745',
    projectId: 'food-delivery-app-31c7f',
    storageBucket: 'food-delivery-app-31c7f.appspot.com',
    iosBundleId: 'com.codeforany.foodDelivery.RunnerTests',
  );
}
